name: smart_swatcher
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.5
  sms_autofill: ^2.4.1
  iconsax: ^0.0.8
  uuid: ^4.5.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  intl: ^0.20.2
  http: ^1.6.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-2.png"
  min_sdk_android: 21

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

#  To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/gifs/
    - assets/images/
    - assets/badges/
    - assets/base/
    - assets/countries_state.json



  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta-Medium.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-Bold.otf
        - asset: assets/fonts/Poppins-Regular.otf
        - asset: assets/fonts/Poppins-Semibold.otf



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
